name: 'Stock Info Bot'

on:
  workflow_dispatch: # 手动触发
  schedule: # 自动触发
    - cron: '1 6,11 * * *'

jobs:
  stock_job:
    name: Stock alert job
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'Starting'
        env: 
          WXHOOK: ${{ secrets.WXHOOK }}
        run: |
          python ./top500.py
